spring.application.name=user-service
server.port=${USER_SERVICE_PORT:8083}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.healthcheck.enabled=true
eureka.client.registry-fetch-interval-seconds=10
eureka.client.initial-instance-info-replication-interval-seconds=10
eureka.client.eureka-server-connect-timeout-seconds=5
eureka.client.eureka-server-read-timeout-seconds=8
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/myrealm}

app.keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8180}
app.keycloak.realm=${KEYCLOAK_REALM:myrealm}
app.keycloak.client-id=${KEYCLOAK_CLIENT_ID:user-service}
app.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:}

app.keycloak.admin-realm=${KEYCLOAK_ADMIN_REALM:master}
app.keycloak.admin-client-id=${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
app.keycloak.admin-client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:}
app.keycloak.admin-username=${KEYCLOAK_ADMIN_USERNAME:admin}
app.keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD:admin}

# OpenFeign Configuration
feign.client.config.default.connect-timeout=5000
feign.client.config.default.read-timeout=5000
feign.client.config.default.encoder=org.springframework.cloud.openfeign.support.SpringEncoder
feign.client.config.default.decoder=org.springframework.cloud.openfeign.support.ResponseEntityDecoder
feign.client.config.default.error-decoder=org.springframework.cloud.openfeign.support.ResponseEntityDecoder

# Feign logging
logging.level.org.springframework.cloud.openfeign.ribbon=DEBUG
logging.level.tn.esprit.userservice.client=DEBUG
