pipeline {
    agent any

    tools {
        jdk 'JDK17'
    }

    environment {
        IMAGE_NAME = "nouhasd/jungledraft"
    }

    stages {

        stage('Build JAR') {
            steps {
                dir('backend/Jungledraft') {
                    sh 'java -version'
                    sh '/usr/bin/mvn clean package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    dir('backend/Jungledraft') {
                        sh '/usr/bin/mvn sonar:sonar'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend/Jungledraft') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                    sh 'docker push $IMAGE_NAME'
                }
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker stop jungledraft || true'
                sh 'docker rm jungledraft || true'
                sh 'docker run -d -p 9090:9090 --name jungledraft $IMAGE_NAME'
            }
        }
    }
}
