pipeline {
    agent any

    tools {
        jdk 'JDK17'
    }

    stages {
        stage('Build') {
            steps {
                dir('backend/Jungledraft') {
                    sh 'java -version'
                    sh '/usr/bin/mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('backend/Jungledraft') {
                    sh '/usr/bin/mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('backend/Jungledraft') {
                    sh '/usr/bin/mvn package'
                }
            }
        }
    }
}
