pipeline {
    agent any

    environment {
        IMAGE_NAME = "nouhasd/jungledraft-frontend:latest"
    }

    stages {

        stage('Install & Build') {
            steps {
                dir('frontend/ProjetPI4eme-newTemplate/ProjetPI4eme-newTemplate') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                        dir('frontend/ProjetPI4eme-newTemplate/ProjetPI4eme-newTemplate') {
                            sh '''
                            npx sonar-scanner \
                              -Dsonar.projectKey=frontend \
                              -Dsonar.sources=. \
                              -Dsonar.host.url=http://192.168.136.153:9000 \
                              -Dsonar.login=$SONAR_TOKEN
                            '''
                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('frontend/ProjetPI4eme-newTemplate/ProjetPI4eme-newTemplate') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Push Docker') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                    sh 'docker push $IMAGE_NAME'
                }
            }
        }

    }
}
