pipeline {
    agent any

    environment {
        IMAGE_NAME = "nouhasd/jungledraft-frontend:latest"
    }

    stages {

        stage('Install & Build') {
            steps {
                dir('frontend/ProjetPI4eme-newTemplate/ProjetPI4eme-newTemplate') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('frontend/ProjetPI4eme-newTemplate/ProjetPI4eme-newTemplate') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Push Docker') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                    sh 'docker push $IMAGE_NAME'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('frontend/ProjetPI4eme-newTemplate/ProjetPI4eme-newTemplate') {
                    sh '''
                    export KUBECONFIG=/var/snap/jenkins/common/.kube/config
                    kubectl apply -f k8s-frontend.yaml --validate=false
                    kubectl rollout restart deployment jungledraft-frontend
                    '''
                }
            }
        }
    }
}
